baseURL = "https://kurtmadel.com"
languageCode = "en-us"
title = "Kurt Madel"
theme = "hemingway2"

copyright = "© 2018 Kurt Madel All Rights Reserved"

googleAnalytics = "UA-119704356-1"
disqusShortname = "kurtmadel-com"

[params]
  AuthorName = "Kurt Madel"
  GitHubUser = "kmadel"
  Subtitle = "Random thoughts on technology and other stuff..."

[taxonomies]
    category = "categories"
    series = "series"
    tags = "tags"

[[params.social]]
url = "https://www.linkedin.com/in/kurt-madel-2304a6a/"
fa_icon = "fa-linkedin"

[[params.social]]
url = "https://github.com/kmadel"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/kmadel"
fa_icon = "fa-twitter"
